### ISSUE TITLE
Use redux-devtools-extension/developmentOnly

### ISSUE THREAD

**Issue by crisfcodes** [treetips/typescript-nextjs-redux-material-ui-example#31]
https://github.com/treetips/typescript-nextjs-redux-material-ui-example/blob/20b76698cd0f7c0cdb85b37980f2b63cf36d086f/store/configureStore.development.ts#L2

You can use [redux-devtools-extension/developmentOnly](https://github.com/zalmoxisus/redux-devtools-extension)  and have a single configuration file (DRY).

**Comment by treetips** [comment]
@cristian05  I'm sorry it took me so long to get back to you.
Thanks for the information.

I know about `redux-devtools-extension/developmentOnly`, but unfortunately, `Google Appengine Standard Environment For Node.js` has a module missing error as shown below.

![devtool](https://user-images.githubusercontent.com/12574048/83346910-b5764580-a35b-11ea-96e5-2debf305a9ed.png)

It's the current bad looking implementation because you have to remove redux-devtools-extension when you build it because it's just present in the source code and it causes an error.

Probably the same is true for `heroku.` I don't know the reason, but I think it's probably because browser functions are not allowed for security reasons.

The only way to solve this problem seems to be to end of support for GAE/Node.js. If you have any information on this subject, please let me know.
